[workspace]

resolver = "2"

members = [
  "crates/wasm",
  "crates/blockifier_utils",
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
license-file = "LICENSE"
repository = "https://github.com/dojoengine/dojo/"
version = "0.2.1"

[workspace.dependencies]
